name: jobgenius

services:
  # Service 1: FastAPI API Server
  api_server:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    container_name: api-server
    image: currybon30/jobgenius-fastapi:2.1.0
    ports:
      - "8000:8000"
    env_file:
      - ./api_server/.env
    depends_on:
      - redis
      - mongodb
      - mysql
      - localstack
      - pinecone
    networks:
      default:
        aliases:
          - api.jobgenius.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    
  # Service 2: Arq Worker for background tasks
  worker:
    container_name: fastapi-worker
    image: currybon30/jobgenius-fastapi:2.1.0
    command: ["arq", "app.bg_worker.WorkerSettings"]
    env_file:
      - ./api_server/.env
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
      - mysql
      - localstack
      - pinecone

  # Service 3: Spring API Server
  auth_server:
    build:
      context: ./auth_server
      dockerfile: Dockerfile
    container_name: auth-server
    image: currybon30/jobgenius-spring:2.1.1
    ports:
      - "5000:5000"
    env_file:
      - ./auth_server/.env
    depends_on:
      - redis
      - mysql
      - api_server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    
  # Service 4: Redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  # Service 5: MongoDB
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ${MONGO_DATA_DIR:-./mongo_data}:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  # Service 6: Pinecone local
  pinecone:
    container_name: pinecone-local
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment: 
      PORT: 5080
      PINECONE_HOST: pinecone.local
    ports: 
      - "5080-5090:5080-5090"
    platform: linux/amd64
    networks:
      default:
        aliases:
          - pinecone.local
    restart: unless-stopped

  # Service 7: MySQL (Alternative run with XAMPP)
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    env_file:
      - ./.env
    volumes:
      - ${MYSQL_DATA_DIR:-./mysql_data}:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    env_file:
      - ./.env
    environment:
      PMA_HOST: ${PHPMYADMIN_MYSQL_HOST}
      PMA_PORT: ${PHPMYADMIN_MYSQL_PORT}
      PMA_USER: ${PHPMYADMIN_MYSQL_USER}
      PMA_PASSWORD: ${PHPMYADMIN_MYSQL_PASSWORD}
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    
  # Service 8: LocalStack
  localstack:
    container_name: localstack
    image: localstack/localstack-pro:latest
    ports:
      - '127.0.0.1:4566:4566' # LocalStack gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
      - '127.0.0.1:443:443' # LocalStack HTTPS Gateway
    env_file:
      - ./.env
    environment:
      # Activate LocalStack for AWS: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${LOCAL_STACK_DEBUG}
      - PERSISTENCE=${LOCAL_STACK_PERSISTENCE}
    volumes:
      - ${LOCALSTACK_DATA_DIR:-./localstack_data}:/var/lib/localstack
      - '/var/run/docker.sock:/var/run/docker.sock' # Docker socket for LocalStack to manage containers
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 1m30s

  # Service 9: Stripe
  stripe:
    container_name: stripe
    image: stripe/stripe-cli:latest
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      auth_server:
        condition: service_healthy
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://auth-server:5000/api/stripe/webhook --skip-update --skip-verify

  # Service 10: Ollama
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_DATA_DIR:-./ollama_data}:/root/.ollama
    networks:
      default:
        aliases:
          - ollama.local
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    pull_policy: always # pull the latest image from the registry
    tty: true # enable TTY for interactive mode
    
    #* GPU resources for ollama (uncomment if you have a GPU)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  #* uncomment if you want to use the ollama webui
  # Service 11: Ollama WebUI 
  # ollama_webui:
  #   container_name: ollama_webui
  #   image: ghcr.io/ollama-webui/ollama-webui:main
  #   ports:
  #     - "11435:8080" # port 8080 is the default port for ollama webui
  #   volumes:
  #     - ${OLLAMA_WEBUI_DATA_DIR:-./ollama_webui_data}:/app/data
  #   depends_on:
  #     - ollama
  #   env_file:
  #     - ./.env
  #   restart: unless-stopped
  #   networks:
  #     default:
  #       aliases:
  #         - ollama_webui.local

volumes:
  mongo_data:
  mysql_data:
  localstack_data:
  ollama_data:
  ollama_webui_data: